service: serverless-dad-joke

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  dadJoke:
    handler: handler.getDadJoke
    events:
      - http:
          path: get-dad-joke
          method: get
          cors: true

custom:
  serverless-offline:
    port: "${env:APP_PORT}"
