service: serverless-dad-joke

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: hello-world
          method: get
          cors: true

custom:
  serverless-offline:
    port: "${env:APP_PORT}"
